CREATE SEQUENCE endereco_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE endereco(
  codigo BIGINT GENERATED BY DEFAULT AS SEQUENCE endereco_id_seq,
  logradouro VARCHAR(255),
  numero INT,
  complemento VARCHAR(255),
  bairro VARCHAR(255),
  cidade VARCHAR(255),
  estado VARCHAR(2),
  pessoa BIGINT NOT NULL,
  FOREIGN KEY (pessoa) REFERENCES pessoa(codigo)
);